// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://arizcblzuonmgstdiscq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFyaXpjYmx6dW9ubWdzdGRpc2NxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczMjkxNzEsImV4cCI6MjA3MjkwNTE3MX0.EONFdZTksRq6MDe8K0LLASUikoJ2CeyIdl0P8H1pbIA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});